---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 14/04/2023 08:51
---
local chat = {}

function chat:new(members, id, messages)
    local instance = {
        members = {},
        id = "",
        messages = {}

    }
    setmetatable(instance, {__index = self})

    return instance
end

function chat:addMember(MemberObj)
    table.insert(self.members, MemberObj)
end

function chat:addMessage(MessageObj)
    print(MessageObj.content, MessageObj.device)
    table.insert(self.messages, MessageObj)
end


return chat