---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 14/04/2023 23:47
---

local device = {}

function device:new(userName, computerID, modemPort)
    local instance = {
        userName = userName,
        computerID = computerID,
        modemPort = modemPort
    }
    setmetatable(instance, {__index = self})

    return instance
end

function device:saveDevices()
    print("Devices Saved")
    return
end

function device:getPort()
    return self.modemPort
end


return device