---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 12/04/2023 23:04
---

local message = {}

function message:new(content, device)
    local instance = {
        content = content,
        device = device
    }
    setmetatable(instance, {__index = self})

    return instance
end

function message:getChat()
    return self.chat
end


return message