---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 12/04/2023 20:46
---

--- Imports

os.loadAPI("API/touchpoint")
local modemAPI = require("API/ModemAPI")
--- Load

local screen = touchpoint.new()
local modem = modemAPI.startModem()
