---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 12/04/2023 23:14
---

--- Imports
local args = {...}
os.loadAPI("API/touchpoint")
local modemAPI = require("../API/ModemAPI")
local mon = peripheral.find("monitor")
--- Load

local tpMon = touchpoint.new("up")
local modem = modemAPI.startModem(tonumber(args[1]))
