---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 12/04/2023 23:14
---

--- Imports
local args = {...}
os.loadAPI("API/touchpoint")
local mon = peripheral.find("monitor")
local modemAPI = require("../API/ModemAPI")

--- Classes

local Chat = require("../Classes/Chat")
local Message = require("../Classes/Message")
local Device = require("../Classes/Device")


--- Load

local tpMon = touchpoint.new("up")
local bridge = modemAPI.startModem(tonumber(args[1]))
local _serverSettingPort = tonumber(args[1])+5
local server = modemAPI.startModem(_serverSettingPort)

while true do
    print("------")
    local channel, receivedMessage = modemAPI.receive()
    if channel == tonumber(args[1]) then
        local ch = Chat:new({}, receivedMessage.id, {})
        for _,v in ipairs(receivedMessage.members) do
            ch:addMember(Device:new(v.userName, v.computerID, v.modemPort))
        end

        for _,t in ipairs(receivedMessage.messages) do
            local user = Device:new(t.device.userName, t.device.computerID, t.device.modemPort)
            ch:addMessage(Message:new(t.content, user))
        end

    elseif channel == _serverSettingPort then

    end
end
