---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by josue.
--- DateTime: 18/04/2023 09:51
---

local chatHandler = {dir = "Server/Chats/"}
local json = require("../Dependencies/Json")

function chatHandler.saveChat(chatObj)
    local chatDir = chatHandler.dir..chatObj.id..".json"
    local f
    if not fs.exists(chatDir) then
        f = fs.open(chatDir, "w")
    end
    if #chatObj.messages > 5 then
        while #chatObj.messages > 5 do
            table.remove(chatObj.messages, 1)
        end
    end

    f = fs.open(chatDir, "w")
    --f.write(textutils.serialize(chatObj))
    f.write(json.encode(chatObj))
    f.flush()
    f.close()
end

function chatHandler.decodeChat(id)
    if tonumber(id) < 11111 then
        return false
    end
    local chatDir = chatHandler.dir..id..".json"
    if fs.exists(chatDir) then
        local f = fs.open(chatDir, "r")
        --local chat = textutils.unserialize(f.readAll())
        local chat = json.decode(f.readAll())
        f.close()
        return chat
    end

    return false
end


return chatHandler